substitutions:
  _REGION: us-central1
  _SERVICE_NAME: user-management-api
  _REPOSITORY: user-management-api-repo
  _IMAGE_NAME: user-management-api
  _IMAGE_TAG: latest
  _APP_ENV: prod
  _LOG_LEVEL: INFO
  _POSTGRES_USER: neondb_owner
  _POSTGRES_HOST: ep-dry-forest-aqsenc2y.c-8.us-east-1.aws.neon.tech
  _POSTGRES_PORT: "5432"
  _POSTGRES_DB: user_management_db
  _POSTGRES_SSLMODE: require

steps:
  - name: python:3.13-slim
    id: Run tests
    entrypoint: bash
    secretEnv:
      - POSTGRES_PASSWORD
    env:
      - APP_ENV=test
      - LOG_LEVEL=INFO
      - POSTGRES_USER=${_POSTGRES_USER}
      - POSTGRES_HOST=${_POSTGRES_HOST}
      - POSTGRES_PORT=${_POSTGRES_PORT}
      - POSTGRES_DB=${_POSTGRES_DB}
      - POSTGRES_SSLMODE=${_POSTGRES_SSLMODE}
    args:
      - -c
      - |
        export POSTGRES_PASSWORD=$$POSTGRES_PASSWORD
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pytest --cov=app

  - name: gcr.io/cloud-builders/docker
    id: Build Docker image
    args:
      - build
      - -t
      - us-central1-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:${_IMAGE_TAG}
      - .

  - name: gcr.io/cloud-builders/docker
    id: Push Docker image
    args:
      - push
      - us-central1-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:${_IMAGE_TAG}

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Deploy to Cloud Run
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image
      - us-central1-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:${_IMAGE_TAG}
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --allow-unauthenticated
      - --set-env-vars
      - APP_ENV=${_APP_ENV},LOG_LEVEL=${_LOG_LEVEL},POSTGRES_USER=${_POSTGRES_USER},POSTGRES_HOST=${_POSTGRES_HOST},POSTGRES_PORT=${_POSTGRES_PORT},POSTGRES_DB=${_POSTGRES_DB},POSTGRES_SSLMODE=${_POSTGRES_SSLMODE}
      - --set-secrets
      - POSTGRES_PASSWORD=neon-postgres-password:latest

images:
  - us-central1-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:${_IMAGE_TAG}

availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/neon-postgres-password/versions/latest
      env: POSTGRES_PASSWORD
